config/routes.rb
TagIt::Application.routes.draw do
  get "sessions/new"

	resources :users do
    member do
      get :following, :followers, :followed_tags
      post :settings
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts, :only => [:create, :show, :edit, :update, :destroy]
  resources :tags, :only => [:index, :show, :destroy]
  
  resources :relationships, :only => [:create, :destroy]
  resources :post_tags, :only => [:create, :destroy]
  resources :user_tags, :only => [:create, :destroy]
  
	root :to => "pages#home"
  
  match "/auth/:provider/callback", to: "sessions#create"
  
	match "/signup" => "users#new"
  match "/signin" => "sessions#new"
  match "/signout" => "sessions#destroy"

	match "/contact" => "pages#contact"
	match "/about" => "pages#about"
	match "/help" => "pages#help"
  match "/news" => "pages#news"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
  
  attr_accessible :name
  
  has_many :post_tags, :class_name => "PostTag", :foreign_key => "tag_id", :dependent => :destroy
  has_many :posts, :through => :post_tags, :source => :post
  
  has_many :user_tags, :class_name => "UserTag", :foreign_key => "tag_id", :dependent => :destroy
  
  validates :name,
    :presence => true,
    :length => { :maximum => 30 },
    :uniqueness => { :case_sensitive => false }
    
  def count
    PostTag.where(:tag_id => id).length
  end
  
  def self.find_or_create_by_name(*args)
    options = args.extract_options!
    options[:name] = args[0] if args[0].is_a?(String)
    case_sensitive = options.delete(:case_sensitive)
    conditions = case_sensitive ? ['name = ?', options[:name]] : ['LOWER(name) = ?', options[:name].downcase] 
    first(:conditions => conditions) || create(options)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :html, :js
  
  def index
    name = "#{params[:name]}%"
    post_id = params[:post_id]
    if post_id.nil?
      @tags = Tag.select('name').where('LOWER(name) LIKE LOWER(?)', name)
    else
      @tags = Tag.select('name').where('LOWER(name) LIKE LOWER(?) AND id NOT IN (SELECT "post_tags".tag_id FROM "post_tags" WHERE "post_tags".post_id = ?)', name, post_id)
    end
    if request.xhr?
      render :partial => 'tags/autocomplete_tag', :collection => @tags.take(5), :post_id => params[:post_id]
    end
  end
  
  def show
    @tag = Tag.find_by_slug(params[:id])
    @tag_posts = Post.where(:id => @tag.posts.uniq).paginate(:page => params[:page]) unless @tag.nil?
    flash[:error] = t(:record_not_found_message) if @tag.nil?
    if request.xhr?
      render :partial => 'posts/post', :collection => @tag_posts
    end
  end
  
  def destroy
    post = Post.find(params[:post_id]) unless params[:post_id].blank?
    current_user.post_tags.find_all_by_tag_id(params[:id]).each(&:destroy)
    redirect_back_or root_path
  end
end

app/views/tags/_autocomplete_tag.html.erb
<div class="tag"><%= autocomplete_tag.name %></div>

app/views/tags/_tag.html.erb
<% unless tag.nil? %>
  <div id="<%= "post_#{local_assigns[:post].id}" unless local_assigns[:post].nil? %>tag_<%= tag.id %>" class="tag">
    <%= render "user_tags/follow_form", :tag => tag if local_assigns[:show_checkboxes] %>
    <%= link_to tag.name, tag %>
    <%= "(#{tag.count})" if local_assigns[:show_count] %>
    <%= link_to "×", tag_path(:id => tag.slug), :method => :delete, :confirm => t(:confirm_untag_all_message) % { :tag => tag.name } if local_assigns[:show_untag_all] %>
  </div>
<% end %>

app/views/tags/_tag_groups.html.erb
<div class="user_tags">
  <div class="tag_group" onclick="toggleCollapsed(this, 'my_tags');">
    <div class="left"><%= t(:my_tags) %></div>
    <div class="expand_button right"></div>
    <div class="clear"></div>
  </div>

  <div id="my_tags" class="tag_group_list" style="display: none">
    <%= render :partial => "tags/tag", :collection => current_user.tags_from_posts, :locals => { :show_checkboxes => true, :show_count => true } %>
  </div>
  <div class="clear"></div>

  <div class="tag_group" onclick="toggleCollapsed(this, 'other_tags');">
    <div class="left"><%= t(:other_tags) %></div>
    <div class="expand_button right"></div>
    <div class="clear"></div>
  </div>

  <div id="other_tags" class="tag_group_list" style="display: none">
    <%= render :partial => "tags/tag", :collection => current_user.tags_from_followed_users - current_user.tags_from_posts, :locals => { :show_checkboxes => true, :show_count => true } %>
  </div>
  <div class="clear"></div>
</div>

app/views/tags/index.html.erb
<% if signed_in? %>
  <%= render "tags/tag_groups", :user => current_user %>
<% else %>
  <%= render :partial => "tags/tag", :collection => Tag.all, :locals => { :show_count => true } %>
  <div class="clear"></div>
<% end %>

app/views/tags/show.html.erb
<% unless @tag.nil? %>
<div id="stream" class="main_bar">
  <div id="tag">
    <%= render "tags/tag", :tag => @tag, :show_untag_all => true %>
    <div class="clear"></div>
  </div>
  
  <div class="posts">
    <%= render "posts/stream", :stream => @tag_posts, :path => tag_path(@tag) %>
  </div>
</div>
<% end %>