config/routes.rb
TagIt::Application.routes.draw do
  get "sessions/new"

	resources :users do
    member do
      get :following, :followers, :followed_tags
      post :settings
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts, :only => [:create, :show, :edit, :update, :destroy]
  resources :tags, :only => [:index, :show, :destroy]
  
  resources :relationships, :only => [:create, :destroy]
  resources :post_tags, :only => [:create, :destroy]
  resources :user_tags, :only => [:create, :destroy]
  
	root :to => "pages#home"
  
  match "/auth/:provider/callback", to: "sessions#create"
  
	match "/signup" => "users#new"
  match "/signin" => "sessions#new"
  match "/signout" => "sessions#destroy"

	match "/contact" => "pages#contact"
	match "/about" => "pages#about"
	match "/help" => "pages#help"
  match "/news" => "pages#news"
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :tag_list
  
  belongs_to :user
  has_many :post_tags, :class_name => 'PostTag', :foreign_key => 'post_id', :dependent => :destroy
  has_many :tags, :through => :post_tags, :source => :tag
  
  validates :title,
    :length => { :maximum => 100 }
  
  validates :content,
    :presence => true,
    :length => { :maximum => 10000 }
  validates :user_id,
    :presence => true
  
  default_scope :order => 'created_at DESC'
  
  def self.per_page
    10
  end
  
  def tag_list(uid = user_id)
    post_tags.find_all_by_user_id(uid).map{ |post_tag| post_tag.tag.name }.join(', ')
  end
  
  def tag_with_list(list, user, destroy_old = true)
    return if list.blank?
  
    post_tags.find_all_by_user_id(user.id).each(&:destroy) if (destroy_old)
    
    tag_names = list.split(/,\s*/)
    new_tags = tag_names.map{ |tag_name| Tag.find_or_create_by_name(tag_name) }
    post_tags.push(new_tags.map{ |new_tag| PostTag.find_or_create_by_post_id_and_tag_id_and_user_id(id, new_tag.id, user.id) })
  end
  
  def tag!(tag, user)
    post_tags.create!(:tag_id => tag.id, :user_id => user.id)
  end
  
  def untag!(tag, user)
    post_tags.find_by_tag_id_and_user_id(tag, user).destroy
  end
  
  def is_tagged?(tag, user)
    post_tags.find_by_tag_id_and_user_id(tag, user)
  end
  
  def tags_for_author
      post_tags
        .select('"tags".name, "post_tags".post_id, "post_tags".tag_id, 0 AS belongs_to_current_user')
        .joins('JOIN "posts" ON "post_tags".post_id = "posts".id')
        .joins('JOIN "tags" ON "post_tags".tag_id = "tags".id')
        .where('"post_tags".user_id = "posts".user_id')
        .order('LOWER("tags".name) ASC')
        .group('"tags".name, "post_tags".post_id, "post_tags".tag_id, belongs_to_current_user')
  end
  
  def tags_for_user(user) # Select ([post tags] for [this user]) + ([post tags] for [author + followed users] except those this user already has)
    post_tags
      .select('"tags".name, "post_tags".post_id, "post_tags".tag_id, (CASE WHEN "post_tags".user_id = ' + user.id.to_s + ' THEN 1 ELSE 0 END) AS belongs_to_current_user')
      .joins('JOIN "posts" ON "post_tags".post_id = "posts".id')
      .joins('JOIN "tags" ON "post_tags".tag_id = "tags".id')
      .joins('LEFT JOIN "relationships" ON "post_tags".user_id = "relationships".followed_id')
      .where('"post_tags".user_id = ? OR (("post_tags".user_id = "posts".user_id OR "relationships".follower_id = ?) AND "post_tags".tag_id NOT IN (SELECT "post_tags".tag_id FROM "post_tags" WHERE "post_tags".post_id = "posts".id AND "post_tags".user_id = ?))', user.id, user.id, user.id)
      .order('LOWER("tags".name) ASC')
      .group('"tags".name, "post_tags".post_id, "post_tags".tag_id, belongs_to_current_user')
  end
  
  def is_collapsed_by(user)
    user.settings.collapse_posts == "true" || (!user.settings.collapsed_posts.nil? && user.settings.collapsed_posts.include?(id))
  end
  
  def self.from_followed_users(user)      
    Post.where(:user_id => user.following_ids)
  end
  
  def self.from_user_stream(user) # Select [posts] from [this user + followed users + tagged posts] that have [tags this user has not blocked]
    Post
      .select('DISTINCT "posts".id, "posts".*')
      .joins('LEFT JOIN "relationships" ON "posts".user_id = "relationships".followed_id')
      .joins('LEFT JOIN "post_tags" ON "posts".id = "post_tags".post_id')
      .joins('LEFT JOIN "user_tags" ON "post_tags".tag_id = "user_tags".tag_id')
      .where('("posts".user_id = ? OR "relationships".follower_id = ? OR "post_tags".user_id = ?) AND "user_tags".tag_id IS NULL', user.id, user.id, user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy
  
  respond_to :html, :js
  
  def create
    if params[:commit] == t(:post_verb) #Create new post
      @post = current_user.posts.build(:title => params[:post][:title], :content => params[:post][:content])
      if @post.save
        @post.tag_with_list(params[:post][:tag_list], current_user)
        respond_with @post
      else
        if @post.valid?
          flash[:error] = t(:post_failed_message)
        else
          flash[:error] = @post.errors.full_messages
        end
        @post = nil
        respond_with @post
      end
    elsif params[:commit] == t(:search_verb) #Search stream
      search
    end
  end
  
  def search
    if params[:post][:title].blank? && params[:post][:content].blank? && params[:post][:tag_list].blank? #No search parameters - reset to default
      @stream = current_user.stream.paginate(:page => params[:page])
    else
      title = "%#{params[:post][:title]}%";
      content = "%#{params[:post][:content]}%";
      tag_names = params[:post][:tag_list].split(/,\s*/).map(&:downcase)
      if tag_names.blank?
        @stream = current_user.stream
          .where('LOWER("posts".title) LIKE LOWER(?) AND LOWER("posts".content) LIKE LOWER(?)', title, content)
          .paginate(:page => params[:page])
      else
        tag_ids = Tag.select('id').where('LOWER(name) in (?)', tag_names)
        if tag_ids.blank?
          @stream = []
        else
          @stream = current_user.stream
            .where('
              LOWER("posts".title) LIKE LOWER(?) AND
              LOWER("posts".content) LIKE LOWER(?) AND
              (SELECT COUNT(DISTINCT "post_tags".tag_id)
              FROM "post_tags"
              WHERE "post_tags".post_id = "posts".id AND "post_tags".tag_id IN (?)) = ?', title, content, tag_ids, tag_ids.length)
            .paginate(:page => params[:page])
        end
      end
    end
    flash[:error] = t(:no_results_found_message) if @stream.blank?
    respond_with @stream
  end
  
  def show
    @post = Post.find_by_id(params[:id])
  end
  
  def edit
    @post = Post.find_by_id(params[:id])
    respond_with @post
  end
  
  def update
    @post = Post.find_by_id(params[:id])
    if @post.update_attributes(:title => params[:post][:title], :content => params[:post][:content])
      @post.tag_with_list(params[:post][:tag_list], current_user)
      respond_with @post
    else
      if @post.valid?
        flash[:error] = t(:post_failed_message)
      else
        flash[:error] = @post.errors.full_messages
      end
      @post = nil
      respond_with @post
    end
  end
  
  def destroy
    @post_id = @post.id
    @post.destroy
    respond_with @post_id
  end
  
  private
    def authorized_user
      @post = current_user.posts.find_by_id(params[:id])
      redirect_to root_path if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  require 'open-uri'
  require 'json'

  NEWLINE_REGEX = /\n/
  WHITESPACE_REGEX = /\s+/
  URL_REGEX = /(http|ftp|https):\/\/(\S*)/i
  IMAGE_URL_REGEX = />((http|ftp|https):\/\/(\S*)\.(jpg|jpeg|gif|png|svg|bmp)(\?[^\\\/\s]+)?)<\/a>/i
  YOUTUBE_REGEX = /<a class="_blank" href="(https?:\/\/(www\.)?(youtube\.com\/watch\?(?:\S+)?(?:v=([\w-]+))(?:\S+)?))">\1<\/a>/i
  VIMEO_REGEX = /<a class="_blank" href="(https?:\/\/(www\.)?(vimeo\.com)\/(\d+))">\1<\/a>/i
  
  def format_post(content, collapsed = false)
    content.gsub!(NEWLINE_REGEX, "<br>") # insert newlines
    content.gsub!(WHITESPACE_REGEX, " ") # insert whitespaces
    content.gsub!(AT_USERNAME_REGEX, link_to("@\\1", users_path + "/\\1") + "\\2") # insert user paths
    content.gsub!(URL_REGEX, '<a class="_blank" href="\\0">\\0</a>') # inser URLs
    
    if !collapsed
      content.gsub!(IMAGE_URL_REGEX, '><img src="\\1" /></a>') # insert images
      content.gsub!(YOUTUBE_REGEX, '<div class="youtube video" src="\\4"><img src="https://img.youtube.com/vi/\\4/0.jpg" /><div class="play_video"></div></div>') # embed youtube
      content.scan(VIMEO_REGEX).each do |match, www, domain, video_id|
        content.sub!(VIMEO_REGEX, '<div class="vimeo video" src="\\4"><img src="' + JSON.parse(open('http://vimeo.com/api/v2/video/' + video_id + '.json').read).first['thumbnail_large'] + '" /><div class="play_video"></div></div>') rescue nil # embed vimeo
      end
    end
    
    simple_format(content)
  end
end

app/views/posts/_fields.html.erb
<%= form_for @post, :remote => true do |f| %>
  <%= render "shared/error_messages", :object => f.object %>
  
  <div class="title">
    <%= f.text_field :title, :placeholder => t(:title) %>
  </div>
  
  <div class="tags tag_list">
    <%= f.text_field :tag_list, :placeholder => t(:tag_list_placeholder), :autocomplete => "off", :onkeyup => "tagListTextBoxKeyUp(event, '" + tags_path + "');" %>
  </div>
  
  <div class="clear"></div>
  
  <div class="content">
    <%= f.text_area :content, :placeholder => t(:new_post_message), :class => "expand50-275" %>
  </div>
  
  <div class="actions">
    <div class="left margin-right">
      <%= f.submit t(:post_verb), :disable_with => t(:post_verb) %>
    </div>
    
    <% if local_assigns[:show_cancel] %>
    <div class="left margin-right">
      <%= submit_tag t(:cancel), :type => "button", :onclick => "$('#post_" + @post.id.to_s + "').replaceWith('" + escape_javascript(render "posts/post", :post => @post) + "');" %>
    </div>
    <% else %>
    <div class="left margin-right">
      <%= f.submit t(:search_verb), :disable_with => t(:search_verb) %>
    </div>
    <% end %>
    
    <div class="clear"></div>
  </div>
  
  <div class="clear"></div>
<% end %>

app/views/posts/_post.html.erb
<div id="post_<%= post.id %>" class="post_item">
  <% post_tag_names = post.tags_for_author.map(&:name) %>
  <% post_is_collapsed = (signed_in? && post.is_collapsed_by(current_user)) || post_tag_names.include?("nsfw") || post_tag_names.include?("18+") || post_tag_names.include?("long") || post_tag_names.include?("adult") || post_tag_names.include?("spoiler") %>
  
  <%= link_to gravatar_for(post.user, :size => 50), post.user %>
  
  <% if signed_in? %>
  <div class="buttons">
    <% if current_user?(post.user) %>
    <div class="delete_button left margin-left">
      <%= link_to "×", post, :method => :delete, :remote => true, :confirm => t(:confirm_delete_message) %>
    </div>
    
    <div class="edit_button left margin-left">
      <%= link_to "✎", edit_post_path(post), :remote => true %>
    </div>
    <% end %>
    
    <%= link_to "", settings_user_path(current_user, :collapse_post => (!post_is_collapsed).to_s, :post_id => post.id), :method => :post, :class => (post_is_collapsed ? "expand" : "collapse") + "_button right margin-left", :remote => true %>
  </div>
  <% end %>
  
  <div class="post">
    <span>
      <a href="<%= user_path(post.user) %>">
        <span class="user_username"><%= post.user.username %></span>
      </a>
    </span>
    <%= link_to(post, :title => post.created_at.to_s(:short), :class => "timestamp") do %>
      <time class="timeago" datetime="<%= post.created_at.iso8601 %>">
        <%= t(:posted_message) % { :time => time_ago_in_words(post.created_at) } %>
      </time>
    <% end %>
    
    <div class="title_and_tags">
      <% unless post.title.blank? %>
      <div class="title"><%= post.title %></div>
      <% end %>
      
      <div class="right">
        <% if signed_in? %>
        <div class="add_tags">
          <div class="tag_list left">
            <input id="post_<%= post.id %>_tag_list_text_box" class="left" type="text" autocomplete="off" onkeyup="tagListTextBoxKeyUp(event, '<%= tags_path %>', <%= post.id %>);" placeholder="<%= t(:tag_list_placeholder_short) %>" />
          </div>
          
          <div class="add_button left">
            <span id="post_<%= post.id %>_show_add_tags" onclick="addTags(this, <%= post.id %>, true);">+</span>
            <%= link_to "+", post_tags_path(:post_id => post.id, :add_tags => true), :method => :post, :remote => true, :id => "post_#{post.id}_add_tags", :style => "display: none", :onclick => "addTags(this, #{post.id}, false);" %>
          </div>
          
          <div class="clear"></div>
        </div>
        <% end %>
        
        <div id="post_<%= post.id %>_tags" class="tags">
          <% if signed_in? %>
            <%= render :partial => "post_tags/post_tag", :collection => post.tags_for_user(current_user) %>
          <% else %>
            <%= render :partial => "post_tags/post_tag", :collection => post.tags_for_author %>
          <% end %>
        </div>
        <div class="clear"></div>
      </div>
      
      <div class="clear"></div>
    </div>
    
    <div class="content">
      <%= format_post(post.content, post_is_collapsed) %>
    </div>
  </div>
  
  <div class="clear"></div>
</div>

app/views/posts/_stream.html.erb
<% unless stream.empty? %>
<%= javascript_include_tag "stream" %>

<div id="filtered_stream" class="posts">
  <%= render :partial => "posts/post", :collection => stream %>
  <%= javascript_include_tag "jquery.pageless.min" %>
  <%= pageless(stream.total_pages, path, "filtered_stream") %>
</div> 
<% end %>

app/views/posts/create.js.erb
//Create
<% unless @post.nil? %>
  $('#filtered_stream').prepend('<%= escape_javascript(render "posts/post", :post => @post) %>');
  $('#post_<%= @post.id %>').toggle(false).animate({ height: 'toggle' }, ANIMATION_DURATION);
  $('#new_post').find('input, textarea').each(function() { $(this).val(''); })
<% end %>

//Search
<% unless @stream.nil? %>
  $('#stream').html('<%= escape_javascript(render "posts/stream", :stream => @stream, :path => root_path) %>');
<% end %>

app/views/posts/destroy.js.erb
<% unless @post_id.nil? %>
  $('#post_<%= @post_id %>').animate({ height: 'toggle' }, ANIMATION_DURATION, function () { $(this).remove(); });
<% end %>

app/views/posts/edit.html.erb
<%= render "posts/fields" %>

app/views/posts/edit.js.erb
<% unless @post.nil? %>
  $('#post_<%= @post.id %>').html('<%= escape_javascript(render "posts/fields", :post => @post, :show_cancel => true) %>');
<% end %>

app/views/posts/show.html.erb
<div id="stream" class="main_bar">
  <%= javascript_include_tag "stream" %>
  <%= render "posts/post", :post => @post %>
</div>
<div class="clear"></div>

app/views/posts/update.js.erb
<% unless @post.nil? %>
  $('#post_<%= @post.id %>').replaceWith('<%= escape_javascript(render "posts/post", :post => @post) %>');
<% end %>