config/routes.rb
TagIt::Application.routes.draw do
  get "sessions/new"

	resources :users do
    member do
      get :following, :followers, :followed_tags
      post :settings
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts, :only => [:create, :show, :edit, :update, :destroy]
  resources :tags, :only => [:index, :show, :destroy]
  
  resources :relationships, :only => [:create, :destroy]
  resources :post_tags, :only => [:create, :destroy]
  resources :user_tags, :only => [:create, :destroy]
  
	root :to => "pages#home"
  
  match "/auth/:provider/callback", to: "sessions#create"
  
	match "/signup" => "users#new"
  match "/signin" => "sessions#new"
  match "/signout" => "sessions#destroy"

	match "/contact" => "pages#contact"
	match "/about" => "pages#about"
	match "/help" => "pages#help"
  match "/news" => "pages#news"
end

app/views/layouts/_footer.html.erb
<footer class="hidden">
  <div class="menu">
    <span><%= link_to t(:about), about_path %></span>
    <span><%= link_to t(:contact), contact_path %></span>
    <span><%= link_to t(:news), news_path %></span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!--<%= link_to logo, root_path %>-->
  
  <div class="menu">
    <% if signed_in? %>
    <span><%= link_to t(:stream), root_path %></span>
    <% end %>
    
    <span><%= link_to t(:tag).pluralize, tags_path %></span>
    <span><%= link_to t(:user).pluralize, users_path %></span>
    
    <% if signed_in? %>
    <span><%= link_to t(:profile), current_user %></span>
    <span><%= link_to t(:setting).pluralize, edit_user_path(current_user) %></span>
    <% end %>
    
    <span class="hidden"><%= link_to t(:help), help_path %></span>
    <span>
      <% if signed_in? %>
        <%= link_to t(:sign_out), signout_path, :method => :delete %>
      <% else %>
        <%= link_to t(:sign_in), signin_path %>
      <% end %>
    </span>
  </div>
  <div class="clear"></div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head profile="http://www.w3.org/2005/10/profile">
    <link rel="icon" type="image/png" href="/images/logo.png" />
    
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag :all, :cache => false, :recursive => true %>
    <%= javascript_include_tag :defaults, "utilities", "jquery.textarea-expander", "jquery.timeago", "google_analytics" %>
  </head>
  
  <body>
    <div id="container">
      <%= render "layouts/header" %>
      
      <div id="section">
        <div id="client_flash"></div>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
        <%= yield %>
      </div>
      
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>